services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mymarket
    ports:
      - "5433:5432"   # было 5432:5432, делаем 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.24.0
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: >
      --url=jdbc:postgresql://db:5432/mymarket
      --username=postgres
      --password=postgres
      --changelog-file=changelog/db.changelog-master.xml
      update

  redis:
    image: redis:7.4.2-bookworm
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
