version: '3.8'
services:
  db:
    image: postgres:16
    container_name: main-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mymarket
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.24.0
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/changelog:/liquibase/changelog:ro
    command: ["liquibase",
              "--url=jdbc:postgresql://main-app:5432/mymarket",
              "--username=postgres",
              "--password=postgres",
              "--changelog-file=/liquibase/changelog/db.changelog-master.xml",
              "update"]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      # Для входа в UI будут использоваться эти параметры
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
